apiVersion: v1
kind: Service
metadata:
  name: {{ include "hutfin-web-fe.fullname" . }}
  labels:
    {{- include "hutfin-web-fe.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.projectName }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.containerPort }}
  type: {{ .Values.service.type }}
  selector:
  {{- include "hutfin-web-fe.selectorLabels" . | nindent 4 }}
